### ISSUE TITLE
Feedback on Changelog

### ISSUE THREAD

**Issue by animeshk08** [Bitergia/release-tools#15]
Hi everyone,
I have recently used the changelog release tool for the following PR: https://github.com/chaoss/grimoirelab-elk/pull/833

Following is my feedback:
* Documentation was good and the tool was easy to use.

* Some guidelines could be made on when/who could write these changelogs. They can be included in CONTRIBUTING.MD file.

* Some use cases specific to the repositories could me mentioned(their links could be specified).

* Also I had a look at @valeriocos feedback of automating the process a bit. I agree creating changelogs via UI of Github is more convenient. Yes, most of the people running this tool will have a good idea of VCS and python itself still I will root for changelogs via UI. Maybe we can have a template made in the PR and create a changelog reading this templates entry once the PR is merged.

* Some work of automating the process of creating a changelog is being done at GitLab itself: https://gitlab.com/gitlab-org/gitlab/-/issues/15148. We can take some inspiration from this.

* Also, I found this section in GitLab's changelog docs. I have not used the tool in such an extent to have a comment, but you guys can have a look so that this tool takes care of all the mentioned problems they faced.
Find the doc here: https://docs.gitlab.com/ee/development/changelog.html#history-and-reasoning

Regarless of the above comments, I love the idea of maintaining a changelog :)

**Comment by sduenas** [comment]
Thanks for your comments. Nothing else to do here.
