### ISSUE TITLE
Running notes with --authors parameter removes the last author

### ISSUE THREAD

**Issue by jjmerchante** [Bitergia/release-tools#46]
When the AUTHORS file doesn't contain an empty line at the end of the file, running `notes "MyPackage" 0.1.0 --authors` removes the last author.

**Comment by vchrombie** [comment]
> When the AUTHORS file doesn't contain an empty line at the end of the file, running `notes "MyPackage" 0.1.0 --authors` removes the last author.

I think we added this feature keeping in mind the file has an extra line in the end, but I think this is an issue.
Thanks for sending the PR @jjmerchante
