### ISSUE TITLE
semverup only upgrades patch version when the notes are FIXED

### ISSUE THREAD

**Issue by sduenas** [Bitergia/release-tools#55]
semverup only upgrades patch version when the notes are FIXED, other kinds of release notes upgrade minor.

We should decide if this is the behaviour we want to increase versions when for example, there are only updates in the linked libraries or dependencies.

**Comment by sduenas** [comment]
Thanks for the time you put on this and the list of suggestions. I comment in line.

> 
> **semverup categories** Based on previous PRs I created a list of where each _release tool category_ should belong.
> 
>     * FIXED: patch

This is the most obvious case. It shouldn't involve a change in the API.

>     * ADDED: minor while not breaking anything

+1

>     * CHANGED: means alter or modify. Implies that something it's not like it was. But it doesn't specify if it will break something or will keep the same output. (minor? major?)

I think we can agree that this implies a change in the API that breaks its usage. This should bump the version to a major.

>     * DEPRECATED: minor

+1

>     * REMOVED: I don't find out an example where something is removed and it is not backward-incompatible (major?)

This should be a major because a feature is gone, so it should mean the API has changed.

>     * SECURITY: minor - patch, it may depend on the security change, if it is to add something or to obfuscate a token for example.

Let's leave this for now in minor.

>     * PERFORMANCE: minor

+1

>     * OTHER: patch

Let's have this a minor. From your list, I saw we only used for updating package dependencies, so, I think we should create a new category for that.

Do you agree with my comments?

**Comment by jjmerchante** [comment]
> Do you agree with my comments?

Yes, I agree. :+1: I create a pull request with those changes and I create a new category for package dependencies.
